spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git: # 使用git的方式
          uri: git@github.com:yx4616/gitee.git
          search-paths: config
server:
  port: 8888
